### ISSUE TITLE
Problem in Android 4.4 WebView

### ISSUE THREAD

**Issue by jonalxh** [RonenNess/ExpiredStorage#1]
Hi, I'm using your library in a web app that is shown through an Android WebView, which uses Chrome 30 version, and it shows me the message: ExpiredStorage: No storage base class provided and 'localStorage' is undefined! Please provide a valid base storage class.
I wanna know why is it happening, I thought it was due the var wasnt created, but I've checked and thats not the reason.

I've to clarify that the web app works in newer browsers.

Hope you could help me

**Comment by RonenNess** [comment]
Hello @jonalxh ,

Luckily, its a really simple problem with a very simple solution :)

**Why it happens**

ExpiredStorage works on top of an existing web storage, either local, session, cookies, or custom user-made storage. Any object that implements getItem(), setItem(), removeItem(), clear() and keys() can be used. 

When you init the expired storage main class, you can either provide a storage type to use, or create it without params in which case the ExpiredStorage will use window.localStorage by default. You can read more about it here:

https://github.com/RonenNess/ExpiredStorage#custom-storage

The error you are getting is because you created an expired storage without params, but when it tried to use window.localStorage as default, it found out localStorage is undefined:

https://github.com/RonenNess/ExpiredStorage/blob/master/dist/expired_storage.js#L14

To validate that this is indeed the problem, you can try adding something like ```console.debug(localStorage)``` to your page, and see that in browsers it will dump the storage to console while in WebView you'll get ```Uncaught ReferenceError: localStorage is not defined```.

**How to fix this**

If you only want to access your page from a specific app you create and have control over, you can enable localStorage in your WebView settings:

```settings.setDomStorageEnabled(true);```

Note that this is from here https://stackoverflow.com/questions/5899087/android-webview-localstorage and this answer is kind of old, so maybe it changed by now.

If you want to make sure all apps will be able to show your page properly (for example twitter or facebook) you might want to add fallbacks to localStorage. see some suggestions here:

https://stackoverflow.com/questions/4692245/html5-local-storage-fallback-solutions

Note that since localStorage is very common I'm pretty sure all serious apps would enable it by default, but if you want to walk on the safe side add fallback. 

Let me know if this was indeed the problem and if my tips helped.

Cheers.

**Comment by jonalxh** [comment]
Hi. Sorry for being late.

Thanks a lot for your so good explanation, It worked like a charm, I was just starting with Android WebViews and ignored it.

Cheers!.

**Comment by RonenNess** [comment]
np, glad I could help!  :)
